name: Chrome headed
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          start: npx cypress run --record --key 4667148f-2a77-4dc1-b0bd-0257380efcd3
          browser: chrome
          